# Temperature is an inference parameter that influences the variability of the responses generated by a foundation model
# It is a way to control the creativity & variability of the model
# A temperature of 0 means no variability - the current version* of the model will return a consistent response to the same prompt
# The higher the temperature, the more variation in responses can be expected

import sys
import boto3

def get_text_response(input_content, temperature): #text-to-text client function
    
    session = boto3.Session()
    bedrock = session.client(service_name='bedrock-runtime')
    
    message = {
        "role": "user",
        "content": [ { "text": input_content } ]
    }
    
    response = bedrock.converse(
        modelId="us.anthropic.claude-3-7-sonnet-20250219-v1:0",
        messages=[message],
        inferenceConfig={
            "maxTokens": 2000,
            "temperature": temperature,
            "topP": 0.9,
            "stopSequences": []
        },
    )
    
    return response['output']['message']['content'][0]['text']


for i in range(3):
    response = get_text_response(sys.argv[1], float(sys.argv[2]))
    print(response, end='\n\n')


# Examples for running this script:

# python3 temperature.py "Write a haiku about a long journey. Skip the preamble:" 0.0
# with a temperature of 0.0, the model generates the same response each time.

# python3 temperature.py "Write a haiku about a long journey. Skip the preamble:" 1.0
# With a temperature above zero, the model should generate a variety of interesting responses
